// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZOqxdUPC5EAKk82_0Mo0xQb1nLnQbVJE',
    appId: '1:658260279625:android:78c05a164dd49c1cf45a98',
    messagingSenderId: '658260279625',
    projectId: 'shopapp-2fcdd',
    databaseURL: 'https://shopapp-2fcdd-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-2fcdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn7fuhKCQ6pGVk9Cu3Vmv9DgNDcW82bEg',
    appId: '1:658260279625:ios:a5b3d5d4af2881bef45a98',
    messagingSenderId: '658260279625',
    projectId: 'shopapp-2fcdd',
    databaseURL: 'https://shopapp-2fcdd-default-rtdb.firebaseio.com',
    storageBucket: 'shopapp-2fcdd.appspot.com',
    iosBundleId: 'com.example.onlineMarket',
  );
}
